### ISSUE TITLE
Framework dependecy is on outdated ask-sdk version 

### ISSUE THREAD

**Issue by vgoldman** [alexa-labs/ask-sdk-frameworks-java#5]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Framework should be up to date on ask-sdk dependency (which is 2.17.2 as of now), and **it should be tested** with the same.

## Current Behavior
Framework is built on top of ask-sdk 2.5.2 and has not been updated in the last 8 months.

## Steps to Reproduce (for bugs)
```
Self-explanatory, build a project with ask-sdk-mvc 0.1.0 and ask-sdk 2.5.2 gets pulled as dependency
```

## Possible Solution
```

```

## Your Environment

* ASK Java Frameworks version used: 0.1.0
* Operating System and version: irrelevant

## Java Info

* Java version used for development: 1.8

**Comment by breedloj** [comment]
Hey Vlad, thanks for reaching out. This frameworks repo contains several plugins that were developed for the core [Alexa Skills Kit SDK for Java](https://github.com/alexa/alexa-skills-kit-sdk-for-java). These plugins are experimental in nature which is why this repo is under the Alexa Labs organization, are not currently under active development, and are not recommended for production skills. The core SDK is fully supported for all skill use cases and is actively supported and maintained by the ASK SDK team.

Some of the features introduced here have been ported to the core SDK, such as the [template resolver feature](https://alexa-skills-kit-sdk-for-java.readthedocs.io/en/latest/Response-Building.html#construct-a-response-with-a-template). If there are other features contained here that you'd like to see brought over feel free to leave a request on the core SDK repo or through [Uservoice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/filters/top?category_id=322783).
